<a href="https://colab.research.google.com/github/KolyaKlimovich/KolyaKlimovich/blob/main/%D0%95%D0%BB%D1%8C%D0%BC%D0%B5%D0%BA%D0%B5%D0%B5%D0%B2_%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/1e3VQ9BR9ShL7E4nGTM2tpW2zmHIfGuxXYcYlkC7YZwU/export?format=csv"
df = pd.read_csv(url)
df.head(5)

,date,last_change_date,total_price,discount_percent,warehouse_name,oblast,nm_id,category,brand,is_cancel,cancel_dt,created_at,updated_at,order_type
0,12.10.2024 5:24,12.10.2024,2329,17,Краснодар,Ростовская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,12.11.2024 18:11,Клиентский
1,12.10.2024 10:45,12.10.2024,2329,17,Казань,Самарская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,12.11.2024 18:11,Клиентский
2,12.10.2024 9:24,12.10.2024,2329,17,Казань,Свердловская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,12.11.2024 18:11,Клиентский
3,12.10.2024 11:53,12.10.2024,2329,17,Электросталь,Тверская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,12.11.2024 18:11,Клиентский
4,05.10.2024 11:14,12.10.2024,2322,21,Казань,Красноярский край,905559214,Товары для животных,e129baf5351375dd,True,12.10.2024,12.11.2024 18:11,12.11.2024 18:11,Клиентский

In [ ]:
# Подсчитать количество каждого значения (True/False) в колонке 'is_cancel'
value_counts = df['is_cancel'].value_counts()

print(value_counts)

is_cancel
False    76241
True      3901
Name: count, dtype: int64

In [ ]:
# Фильтруем и оставляем только строки, где is_cancel == False
df_is_not_cancel = df[df['is_cancel'] == False]

df_is_not_cancel.shape

(76241, 14)

In [ ]:
# Заменил запятую на точку и потом перевел в числовой тип данных
df['total_price1']=df['total_price'].str.replace(',','.').astype(float)

In [ ]:
df['updated_at'] = pd.to_datetime(df['updated_at'], format='%d.%m.%Y %H:%M')
df= df[df['updated_at'] <= '2025-01-01']
df['year_month'] = df['updated_at'].dt.to_period('M')
df

<ipython-input-196-f1a573aabe14>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year_month'] = df['updated_at'].dt.to_period('M')

,date,last_change_date,total_price,discount_percent,warehouse_name,oblast,nm_id,category,brand,is_cancel,cancel_dt,created_at,updated_at,order_type,total_price1,year_month
0,12.10.2024 5:24,12.10.2024,2329,17,Краснодар,Ростовская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,2024-11-12 18:11:00,Клиентский,2329.0,2024-11
1,12.10.2024 10:45,12.10.2024,2329,17,Казань,Самарская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,2024-11-12 18:11:00,Клиентский,2329.0,2024-11
2,12.10.2024 9:24,12.10.2024,2329,17,Казань,Свердловская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,2024-11-12 18:11:00,Клиентский,2329.0,2024-11
3,12.10.2024 11:53,12.10.2024,2329,17,Электросталь,Тверская область,905559214,Товары для животных,e129baf5351375dd,False,NaN,12.11.2024 18:11,2024-11-12 18:11:00,Клиентский,2329.0,2024-11
4,05.10.2024 11:14,12.10.2024,2322,21,Казань,Красноярский край,905559214,Товары для животных,e129baf5351375dd,True,12.10.2024,12.11.2024 18:11,2024-11-12 18:11:00,Клиентский,2322.0,2024-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80137,10.09.2024 1:18,10.09.2024,2136,10,Электросталь,Санкт-Петербург,811003631,Товары для животных,e129baf5351375dd,False,NaN,10.10.2024 18:02,2024-10-10 18:02:00,Клиентский,2136.0,2024-10
80138,10.09.2024 10:38,10.09.2024,2136,10,Электросталь,Архангельская область,811003631,Товары для животных,e129baf5351375dd,False,NaN,10.10.2024 18:02,2024-10-10 18:02:00,Клиентский,2136.0,2024-10
80139,03.10.2024 13:02,08.10.2024,2153,18,Электросталь,Минск,811003631,Товары для животных,e129baf5351375dd,True,08.10.2024,08.11.2024 18:02,2024-11-08 18:02:00,Клиентский,2153.0,2024-11
80140,04.11.2024 8:03,04.11.2024,2394,26,Казань,Самарская область,811003631,Товары для животных,e129baf5351375dd,False,NaN,04.12.2024 18:09,2024-12-04 18:09:00,Клиентский,2394.0,2024-12
80141,22.09.2024 0:47,26.09.2024,2161,17,Электросталь,Москва,811003631,Товары для животных,e129baf5351375dd,True,26.09.2024,26.10.2024 18:02,2024-10-26 18:02:00,Клиентский,2161.0,2024-10

Warning: total number of rows (80068) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
# Группировка по артикулу
df_grouped = df.groupby(['nm_id', 'year_month'], as_index=False).agg(
    total_sales=('total_price1', 'sum'),  # Сумма продаж по артикулу
    count_orders=('total_price1', 'size')  # Количество заказов (строчек) по артикулу
)

# Сортировка по сумме продаж от большого к меньшему
df_grouped = df_grouped.sort_values(by='year_month', ascending=False)

df_grouped

         nm_id year_month  total_sales  count_orders
109  905559214    2024-12    821165.00           393
10   -83054245    2024-12    522033.00           149
54   304773881    2024-12    141180.00           121
32    95166060    2024-12     88719.00           181
65   440376223    2024-12    311508.00           286
..         ...        ...          ...           ...
44   304773881    2024-02   4806006.10          7502
33   126373749    2024-02  13635551.88          6534
22    95166060    2024-02    614753.23          2094
11    44403861    2024-02    499830.93          1146
55   440376223    2024-02   2515424.79          3551

[110 rows x 4 columns]

In [ ]:
df_december_2024 = df_grouped[df_grouped['year_month'] == '2024-12']
df_december_2024[['nm_id', 'total_sales', 'count_orders']].sort_values(by='nm_id')

         nm_id  total_sales  count_orders
10   -83054245     522033.0           149
21    44403861    1093378.0          1963
32    95166060      88719.0           181
43   126373749    1021042.0           342
54   304773881     141180.0           121
65   440376223     311508.0           286
76   678167538     455482.0           129
87   811003631     313494.0           131
98   879714109     222481.0           335
109  905559214     821165.0           393

In [ ]:
df_november_2024 = df_grouped[df_grouped['year_month'] == '2024-11']
df_november_2024[['nm_id', 'total_sales', 'count_orders']].sort_values(by='nm_id')

         nm_id  total_sales  count_orders
9    -83054245     500030.0           143
20    44403861     703254.0          1267
31    95166060      97619.0           200
42   126373749     888296.0           330
53   304773881     108729.0           100
64   440376223     386702.0           355
75   678167538     400656.0           148
86   811003631     292429.0           132
97   879714109     219716.0           331
108  905559214     820083.0           361

In [ ]:
df_october_2024 = df_grouped[df_grouped['year_month'] == '2024-10']
df_october_2024[['nm_id', 'total_sales', 'count_orders']].sort_values(by='nm_id')

         nm_id  total_sales  count_orders
8    -83054245     314509.0            98
19    44403861      36834.0            69
30    95166060      87685.0           179
41   126373749     645828.0           247
52   304773881      78956.0            79
63   440376223     286204.0           248
74   678167538     289457.0           109
85   811003631     263093.0           123
96   879714109     267259.0           387
107  905559214     739860.0           320

In [ ]:
# Метод взвешенных средних (Exponentially Weighted Moving Average)
# Этот метод придаёт больший вес более недавним данным, что позволяет лучше учесть изменения трендов.

# Вычисляем EWMA для total_sales и count_orders для каждого товара
df_grouped['ewma_sales'] = df_grouped.groupby('nm_id')['total_sales'].transform(lambda x: x.ewm(span=3, adjust=False).mean())
df_grouped['ewma_orders'] = df_grouped.groupby('nm_id')['count_orders'].transform(lambda x: x.ewm(span=3, adjust=False).mean())

In [ ]:
df_grouped

,nm_id,year_month,total_sales,count_orders,ewma_sales,ewma_orders
109,905559214,2024-12,821165.00,393,8.211650e+05,393.000000
10,-83054245,2024-12,522033.00,149,5.220330e+05,149.000000
54,304773881,2024-12,141180.00,121,1.411800e+05,121.000000
32,95166060,2024-12,88719.00,181,8.871900e+04,181.000000
65,440376223,2024-12,311508.00,286,3.115080e+05,286.000000
...,...,...,...,...,...,...
44,304773881,2024-02,4806006.10,7502,2.474245e+06,3849.081055
33,126373749,2024-02,13635551.88,6534,7.121143e+06,3392.154297
22,95166060,2024-02,614753.23,2094,3.469623e+05,1177.620117
11,44403861,2024-02,499830.93,1146,2.897505e+05,676.222656
55,440376223,2024-02,2515424.79,3551,1.387285e+06,1936.559570

In [ ]:
# Теперь можно сгруппировать по товарам и рассчитать план продаж для января 2025 года
# Прогноз на январь 2025 = последние значения EWMA для каждого товара
df_forecast = df_grouped.groupby('nm_id').head(1)[['nm_id', 'ewma_sales', 'ewma_orders']]

# Переименуем столбцы для финального вывода
df_forecast = df_forecast.rename(columns={'ewma_sales': 'forecast_sales_jan_2025', 'ewma_orders': 'forecast_orders_jan_2025'})

# Округляем значения в столбцах до целых чисел
df_forecast[['forecast_sales_jan_2025', 'forecast_orders_jan_2025']] = \
    df_forecast[['forecast_sales_jan_2025', 'forecast_orders_jan_2025']].round(0).astype(int)

# Выводим итоговый результат
df_forecast[['nm_id', 'forecast_sales_jan_2025', 'forecast_orders_jan_2025']].sort_values(by='nm_id')

         nm_id  forecast_sales_jan_2025  forecast_orders_jan_2025
10   -83054245                   522033                       149
21    44403861                  1093378                      1963
32    95166060                    88719                       181
43   126373749                  1021042                       342
54   304773881                   141180                       121
65   440376223                   311508                       286
76   678167538                   455482                       129
87   811003631                   313494                       131
98   879714109                   222481                       335
109  905559214                   821165                       393